### ISSUE TITLE
non existing repository in install.sh

### ISSUE THREAD

**Issue by rbazan1** [rollingcoconut/hadoopExprOnGeni#1]
Line 41 in  hadoopExprOnGeni/install.sh is pointing to an non existing repository
_wget https://nyu.box.com/shared/static/kbzerbhp2mjktamvrmpiazikg58568ho.zip_

**Comment by ffund** [comment]
Thanks for letting us know. We're going to move this file to a more stable file storage service, and update the link in the script. In the meantime, access via Box.com has been temporarily restored so that you can run the experiment as is.
